### ISSUE TITLE
Possible version incompatibility

### ISSUE THREAD

**Issue by yschimke** [jetty-project/jetty-alpn#26]
https://github.com/square/okhttp/issues/4423#issuecomment-443064924

Flagging, but might be red herring at the moment.

**Comment by sbordet** [comment]
@yschimke it's a known problem reported in #22 and eclipse/jetty.project#3100.

Debian has screwed up the backports and created OpenJDK versions that are a mix of 8u181 and 8u191 but not really the former nor the latter.

Best option is to use the official OpenJDK builds, not Debian's or Ubuntu's - also because there is no need for the Debian backports now that OpenJDK 8u191/8u192 are out (but not released by Debian yet?!?).
